name: Issue Comment Created Triage

on:
  issue_comment:
    types: [created]

jobs:
  community_check:
    uses: ./.github/workflows/community-check.yml
    secrets: inherit

  issue_comment_triage:
    name: 'Remove stale and waiting-response Labels on Response'
    needs: community_check
    if: github.event_name == 'issue_comment' && needs.community_check.outputs.maintainer == 'false'
    uses: ./.github/workflows/reusable-add-or-remove-labels.yml
    with:
      remove: stale,waiting-response
