name: Issue Comment Created Triage

on:
  issue_comment:
    types: [created]

env:
  IN_MAINTAINER_LIST: ${{ contains(secrets.MAINTAINER_LIST, github.actor) }}

jobs:
  issue_comment_triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0
        if: github.event_name == 'issue_comment' && env.IN_MAINTAINER_LIST == 'false'
        with:
          labels: |
            stale
            waiting-response
