name: YAML Linting
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - "**/*.yml"
      - ".yamllint"
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          format: github
        env:
          LANG: C.UTF-8
